-- CREATE VIEW temp AS
-- (
-- SELECT SCELL,NCELL,C2I_Mean
-- FROM 1tbcell ,10tbc2i
-- WHERE(LONGITUDE BETWEEN 112 AND 113 )AND(LATITUDE BETWEEN 33.7 AND 33.9)AND(1tbcell.`SECTOR_ID`= 10tbc2i.`SCELL`)
-- )

SELECT NCELL
FROM  temp
WHERE  C2I_Mean >= ALL(SELECT C2I_Mean
			FROM temp)
			